# Generated by Django 5.2.2 on 2025-08-02 01:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='storage_plans/')),
                ('description', models.TextField()),
                ('buying_price_per_bag', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('projected_selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('storage_due_date', models.DateField()),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('maximum_quantity', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('storage_cost_per_bag', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Storage Plan',
                'verbose_name_plural': 'Storage Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('quantity_bags', models.PositiveIntegerField()),
                ('price_per_bag', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_investment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('projected_selling_price_per_bag', models.DecimalField(decimal_places=2, max_digits=12)),
                ('projected_returns', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active Storage'), ('matured', 'Ready for Sale'), ('completed', 'Sold & Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storageinvestments', to=settings.AUTH_USER_MODEL)),
                ('storage_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storageinvestments', to='storage.storageplan')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_gateway', models.CharField(default='paystack', max_length=50)),
                ('gateway_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='storage.storageinvestment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_type', models.CharField(choices=[('storage_start', 'Storage Started'), ('quality_check', 'Quality Check'), ('price_update', 'Price Update'), ('maturity', 'Product Matured'), ('sale_complete', 'Sale Completed'), ('general', 'General Update')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('current_market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='storage_updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='storage.storageinvestment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
