# Generated by Django 5.2.2 on 2025-08-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageinvestment',
            name='matured_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
