# Generated by Django 5.2.2 on 2025-08-21 08:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storageinvestment_matured_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageplan',
            name='product_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='storageupdate',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
