# Generated by Django 5.2.2 on 2025-08-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_withdrawalrequest_investment_withdrawal_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='investments',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='investments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='investments.investment'),
        ),
    ]
