# Generated by Django 5.2.2 on 2025-08-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_withdrawalrequest_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
    ]
