# Generated by Django 5.2.2 on 2025-08-18 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_bankaccount_recipient_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bank_code',
            new_name='bank_name',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='transfer_code',
        ),
    ]
