# Generated by Django 5.2.2 on 2025-08-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_rename_bank_code_bankaccount_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='recipient_code',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
