# Generated by Django 5.2.2 on 2025-08-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_remove_bankaccount_recipient_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='investments',
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='investments',
            field=models.ManyToManyField(blank=True, null=True, related_name='withdrawal_requests', to='investments.investment'),
        ),
    ]
