# Generated by Django 5.2.2 on 2025-08-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_remove_withdrawalrequest_investments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=30),
        ),
    ]
