# Generated by Django 5.2.6 on 2025-10-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_bankaccount_created_at_bankaccount_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='investments',
            field=models.ManyToManyField(blank=True, related_name='withdrawal_requests', to='investments.investment'),
        ),
    ]
